# Generated by Django 3.0.3 on 2020-02-09 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_ja', models.CharField(blank=True, max_length=100)),
                ('title_ko', models.CharField(blank=True, max_length=100)),
                ('title_zh', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('description_ja', models.TextField(blank=True)),
                ('description_ko', models.TextField(blank=True)),
                ('description_zh', models.TextField(blank=True)),
                ('photo_main', models.ImageField(upload_to='photos/services/')),
                ('display_top', models.BooleanField(default=False)),
            ],
        ),
    ]
