# Generated by Django 3.0.3 on 2020-02-12 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('title_ja', models.CharField(max_length=120)),
                ('title_zh', models.CharField(max_length=120)),
                ('title_ko', models.CharField(max_length=120)),
                ('transmission', models.CharField(choices=[('AUTOMATIC', 'Automatic'), ('MANUAL', 'Manual')], max_length=120)),
                ('body_type', models.CharField(choices=[('COUPE', 'Coupe'), ('HATCHBACK', 'Hatchback'), ('PEOPLE_MOVER', 'People Mover'), ('RV_SUV', 'RV/SUV'), ('SEDAN', 'Sedan'), ('STATION_WAGON', 'Station Wagon'), ('VAN', 'Van')], max_length=120)),
                ('doors', models.PositiveIntegerField()),
                ('seats', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('fuel_rate', models.PositiveIntegerField()),
                ('safety_rate', models.PositiveIntegerField()),
                ('fuel_cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('color', models.CharField(max_length=20)),
                ('energy_source', models.CharField(choices=[('PETROL', 'Petrol'), ('DESEL', 'Desel'), ('ELECTRIC', 'Electric'), ('HYBRID', 'Hybrid')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_ja', models.CharField(max_length=100)),
                ('name_zh', models.CharField(max_length=100)),
                ('name_ko', models.CharField(max_length=100)),
                ('cars', models.ManyToManyField(related_name='features', to='cars.Car')),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Manufacturer')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.CarModel'),
        ),
    ]
