# Generated by Django 3.0.3 on 2020-02-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20200213_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='cars',
        ),
        migrations.AddField(
            model_name='car',
            name='features',
            field=models.ManyToManyField(related_name='cars', to='cars.Feature'),
        ),
    ]
