# Generated by Django 3.0.3 on 2020-02-12 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20200213_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='content',
        ),
        migrations.RemoveField(
            model_name='car',
            name='email',
        ),
        migrations.RemoveField(
            model_name='car',
            name='title_ja',
        ),
        migrations.RemoveField(
            model_name='car',
            name='title_ko',
        ),
        migrations.RemoveField(
            model_name='car',
            name='title_zh',
        ),
        migrations.AddField(
            model_name='car',
            name='engine_size',
            field=models.PositiveIntegerField(default=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='car',
            name='photo_2',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='car',
            name='photo_3',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='car',
            name='photo_4',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='car',
            name='photo_5',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='car',
            name='photo_6',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='car',
            name='photo_main',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
