# Generated by Django 3.0.3 on 2020-02-12 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20200213_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photo_main',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/'),
        ),
    ]
