# Generated by Django 3.0.3 on 2020-02-13 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20200213_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='photo_1',
        ),
        migrations.RemoveField(
            model_name='car',
            name='photo_2',
        ),
        migrations.RemoveField(
            model_name='car',
            name='photo_3',
        ),
        migrations.RemoveField(
            model_name='car',
            name='photo_4',
        ),
        migrations.RemoveField(
            model_name='car',
            name='photo_5',
        ),
        migrations.RemoveField(
            model_name='car',
            name='photo_6',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='cars.Car')),
            ],
        ),
    ]
