# Generated by Django 3.0.3 on 2020-02-14 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_auto_20200214_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='cars', to='cars.Feature'),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_rate',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='safety_rate',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
