# Generated by Django 3.0.3 on 2020-02-14 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_auto_20200214_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='odo',
            field=models.PositiveIntegerField(default=50000),
            preserve_default=False,
        ),
    ]
