# Generated by Django 3.0.3 on 2020-02-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_car_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_rate',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='car',
            name='safety_rate',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2),
        ),
    ]
